namespace: ingress

apps:
  - name: app0
    image: nginx
    replicas: 2
  - name: app1
    image: nginx
    replicas: 2
  - name: app2
    image: nginx
    replicas: 2

ingress:
  enabled: true
  host: empty-planet.com
  tlsSecret: empty-planet-tls
  issuerName: letsencrypt-prod

clusterIssuer:
  enabled: true
  email: prakharsingh1932003@gmai.com
  secretName: letsencrypt-prod-account-key
