apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: prakhar0819/k8s-testing:app2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
